//
// Milkyway Hierarchical Verilog Dump:
// Generated on 02/27/2019 at 10:16:33
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :s386.mw
// Cell Name    :s386
// Hierarchy delimiter:'/'
// Write Command : write_verilog ./output/s386_extracted.v
//


module s386 (GND , v5 , v4 , v3 , v2 , v1 , v0 , CK , VDD , 
    v13_D_9 , v13_D_8 , v13_D_7 , v13_D_6 , v13_D_12 , v13_D_11 , 
    v13_D_10 , v6 );
input  GND ;
input  v5 ;
input  v4 ;
input  v3 ;
input  v2 ;
input  v1 ;
input  v0 ;
input  CK ;
input  VDD ;
output v13_D_9 ;
output v13_D_8 ;
output v13_D_7 ;
output v13_D_6 ;
output v13_D_12 ;
output v13_D_11 ;
output v13_D_10 ;
input  v6 ;



OR2X1_RVT U69 (.Y ( n93 ) , .A2 ( n90 ) , .A1 ( n104 ) ) ;
OAI21X1_RVT U68 (.Y ( v13_D_9 ) , .A3 ( n98 ) , .A2 ( n58 ) , .A1 ( n95 ) ) ;
DFFX1_RVT \DFF_5/q_reg (.QN ( n101 ) , .D ( Lv13_D_0 ) , .CLK ( CK ) , .Q ( v7 ) ) ;
DFFX1_RVT \DFF_3/q_reg (.QN ( n104 ) , .D ( Lv13_D_2 ) , .CLK ( CK ) , .Q ( v9 ) ) ;
DFFX1_RVT \DFF_0/q_reg (.QN ( n102 ) , .D ( Lv13_D_5 ) , .CLK ( CK ) , .Q ( v12 ) ) ;
DFFX1_RVT \DFF_2/q_reg (.QN ( n105 ) , .D ( Lv13_D_3 ) , .CLK ( CK ) , .Q ( v10 ) ) ;
DFFX1_RVT \DFF_4/q_reg (.QN ( n103 ) , .D ( Lv13_D_1 ) , .CLK ( CK ) , .Q ( v8 ) ) ;
DFFX1_RVT \DFF_1/q_reg (.QN ( n106 ) , .D ( Lv13_D_4 ) , .CLK ( CK ) , .Q ( v11 ) ) ;
NAND2X0_RVT U77 (.A2 ( n75 ) , .A1 ( v8 ) , .Y ( n69 ) ) ;
AND3X1_RVT U76 (.A1 ( v3 ) , .Y ( n61 ) , .A2 ( n101 ) , .A3 ( n106 ) ) ;
AND2X1_RVT U75 (.Y ( n79 ) , .A1 ( n81 ) , .A2 ( n102 ) ) ;
INVX0_RVT U74 (.A ( n69 ) , .Y ( n56 ) ) ;
INVX0_RVT U73 (.A ( n64 ) , .Y ( n97 ) ) ;
OA221X1_RVT U72 (.A1 ( v12 ) , .A4 ( v2 ) , .A2 ( v4 ) , .A5 ( n88 ) , .Y ( n80 ) 
    , .A3 ( v12 ) ) ;
AO22X1_RVT U71 (.A2 ( v5 ) , .A3 ( n106 ) , .Y ( n77 ) , .A4 ( n73 ) 
    , .A1 ( n74 ) ) ;
INVX0_RVT U70 (.A ( n66 ) , .Y ( n72 ) ) ;
AND3X1_RVT U85 (.A1 ( n103 ) , .Y ( n88 ) , .A2 ( n101 ) , .A3 ( n106 ) ) ;
NAND4X0_RVT U84 (.A2 ( n57 ) , .A4 ( n83 ) , .A3 ( n56 ) , .Y ( n58 ) 
    , .A1 ( v4 ) ) ;
AND2X1_RVT U83 (.Y ( n57 ) , .A1 ( n101 ) , .A2 ( n106 ) ) ;
NAND3X0_RVT U82 (.Y ( n95 ) , .A1 ( n102 ) , .A2 ( n105 ) , .A3 ( n104 ) ) ;
INVX0_RVT U81 (.A ( v5 ) , .Y ( n67 ) ) ;
INVX0_RVT U80 (.A ( v0 ) , .Y ( n92 ) ) ;
INVX0_RVT U79 (.A ( v1 ) , .Y ( n83 ) ) ;
INVX0_RVT U78 (.A ( v3 ) , .Y ( n75 ) ) ;
NOR4X1_RVT U93 (.Y ( n64 ) , .A4 ( v3 ) , .A2 ( v4 ) , .A3 ( v11 ) , .A1 ( n103 ) ) ;
AND4X1_RVT U92 (.Y ( v13_D_10 ) , .A1 ( v1 ) , .A3 ( n60 ) , .A4 ( n59 ) 
    , .A2 ( v9 ) ) ;
AO21X1_RVT U91 (.A1 ( v0 ) , .Y ( n59 ) , .A2 ( v5 ) , .A3 ( n105 ) ) ;
NOR2X0_RVT U90 (.Y ( v13_D_8 ) , .A2 ( n98 ) , .A1 ( v6 ) ) ;
NOR3X0_RVT U89 (.Y ( v13_D_12 ) , .A1 ( n105 ) , .A3 ( n93 ) , .A2 ( n67 ) ) ;
NAND3X0_RVT U88 (.Y ( n90 ) , .A1 ( n88 ) , .A2 ( n102 ) , .A3 ( n92 ) ) ;
NAND4X0_RVT U87 (.A2 ( v0 ) , .A4 ( n104 ) , .A3 ( n60 ) , .Y ( n98 ) 
    , .A1 ( v10 ) ) ;
AND2X1_RVT U86 (.Y ( n60 ) , .A1 ( n88 ) , .A2 ( n102 ) ) ;
NAND3X0_RVT U101 (.Y ( n63 ) , .A1 ( n79 ) , .A2 ( v8 ) , .A3 ( n62 ) ) ;
AO22X1_RVT U100 (.A2 ( v11 ) , .A3 ( v2 ) , .Y ( n62 ) , .A4 ( n61 ) , .A1 ( v7 ) ) ;
NAND4X0_RVT U99 (.A2 ( n81 ) , .A4 ( n101 ) , .A3 ( n74 ) , .Y ( n66 ) 
    , .A1 ( v12 ) ) ;
OA221X1_RVT U98 (.A1 ( n64 ) , .A4 ( n96 ) , .A2 ( v11 ) , .A5 ( n79 ) 
    , .Y ( Lv13_D_0 ) , .A3 ( n64 ) ) ;
NAND2X0_RVT U97 (.A2 ( v7 ) , .A1 ( v8 ) , .Y ( n96 ) ) ;
OA221X1_RVT U96 (.A1 ( n64 ) , .A4 ( n74 ) , .A2 ( v7 ) , .A5 ( n79 ) 
    , .Y ( v13_D_7 ) , .A3 ( n64 ) ) ;
AND4X1_RVT U95 (.Y ( n81 ) , .A1 ( n105 ) , .A3 ( n83 ) , .A4 ( v0 ) 
    , .A2 ( n104 ) ) ;
AND2X1_RVT U94 (.Y ( n74 ) , .A1 ( v11 ) , .A2 ( n103 ) ) ;
AO21X1_RVT U109 (.A1 ( v8 ) , .Y ( n73 ) , .A2 ( v3 ) , .A3 ( v4 ) ) ;
AO22X1_RVT U108 (.A2 ( v5 ) , .A3 ( n71 ) , .Y ( v13_D_6 ) , .A4 ( n106 ) 
    , .A1 ( n72 ) ) ;
AND2X1_RVT U107 (.Y ( n71 ) , .A1 ( n79 ) , .A2 ( n70 ) ) ;
AO222X1_RVT U106 (.A1 ( v7 ) , .A5 ( n69 ) , .A6 ( v2 ) , .A3 ( v7 ) 
    , .A2 ( n69 ) , .Y ( n70 ) , .A4 ( v4 ) ) ;
AO22X1_RVT U105 (.A2 ( n68 ) , .A3 ( n72 ) , .Y ( Lv13_D_4 ) , .A4 ( n67 ) 
    , .A1 ( n79 ) ) ;
NAND3X0_RVT U104 (.Y ( n68 ) , .A1 ( n101 ) , .A2 ( n97 ) , .A3 ( n65 ) ) ;
NAND3X0_RVT U103 (.Y ( n65 ) , .A1 ( v2 ) , .A2 ( n103 ) , .A3 ( n106 ) ) ;
NAND2X0_RVT U102 (.A2 ( n63 ) , .A1 ( n66 ) , .Y ( Lv13_D_5 ) ) ;
OR2X1_RVT U117 (.Y ( n85 ) , .A2 ( n84 ) , .A1 ( v10 ) ) ;
AND2X1_RVT U116 (.Y ( n84 ) , .A1 ( v0 ) , .A2 ( n83 ) ) ;
AO21X1_RVT U115 (.A1 ( v9 ) , .Y ( n86 ) , .A2 ( v0 ) , .A3 ( n82 ) ) ;
OR2X1_RVT U114 (.Y ( n82 ) , .A2 ( v7 ) , .A1 ( v8 ) ) ;
NAND2X0_RVT U113 (.A2 ( n104 ) , .A1 ( n102 ) , .Y ( n87 ) ) ;
AO22X1_RVT U112 (.A2 ( n80 ) , .A3 ( n79 ) , .Y ( Lv13_D_1 ) , .A4 ( n78 ) 
    , .A1 ( n81 ) ) ;
AO22X1_RVT U111 (.A2 ( n77 ) , .A3 ( n101 ) , .Y ( n78 ) , .A4 ( n76 ) 
    , .A1 ( v7 ) ) ;
AOI221X1_RVT U110 (.Y ( n76 ) , .A3 ( n106 ) , .A2 ( n75 ) , .A4 ( v2 ) 
    , .A1 ( n106 ) , .A5 ( n103 ) ) ;
NAND3X0_RVT U125 (.Y ( v13_D_11 ) , .A1 ( n100 ) , .A2 ( n99 ) , .A3 ( n98 ) ) ;
AO221X1_RVT U124 (.A5 ( n95 ) , .A1 ( n97 ) , .A4 ( n96 ) , .Y ( n99 ) 
    , .A2 ( n106 ) , .A3 ( n97 ) ) ;
NAND2X0_RVT U123 (.A2 ( n100 ) , .A1 ( n94 ) , .Y ( Lv13_D_2 ) ) ;
OA22X1_RVT U122 (.Y ( n94 ) , .A4 ( n91 ) , .A3 ( n92 ) , .A2 ( n93 ) 
    , .A1 ( v5 ) ) ;
NAND3X0_RVT U121 (.Y ( Lv13_D_3 ) , .A1 ( n100 ) , .A2 ( n90 ) , .A3 ( n89 ) ) ;
AO221X1_RVT U120 (.A5 ( n91 ) , .A1 ( v9 ) , .A4 ( n105 ) , .Y ( n89 ) 
    , .A2 ( v5 ) , .A3 ( v9 ) ) ;
NAND3X0_RVT U119 (.Y ( n91 ) , .A1 ( v1 ) , .A2 ( n88 ) , .A3 ( n102 ) ) ;
AO21X1_RVT U118 (.A1 ( n87 ) , .Y ( n100 ) , .A2 ( n86 ) , .A3 ( n85 ) ) ;
endmodule


